---
title: "Exploración Plantas Extintas"
author: "Allen"
date: "12-05-2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE,warning = FALSE)
library(tidyverse)
library(kableExtra)
library(knitr)
```
## Introcucción

### De donde vienen los datos

Estos datos sobre plantas extintas son datos de la **IUCN**, y se obtuvieron 
del [siguiente  repositorio](https://github.com/rfordatascience/tidytuesday) github


```{r,echo=FALSE, message=FALSE, warning=FALSE}
plantas  <-  readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv')
acciones  <-  readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv')
amenazas  <-  readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv')
```

## Datos de Sudamérica

El número de especies que hay en sudamerica en la base de datos es de `r plantas %>% dplyr::filter(continent=="South America") %>% nrow()` especies


```{r}
data("msleep")
view(msleep)
Tabla <- msleep %>% group_by(vore) %>%  
  summarise_at("sleep_total",.funs=list(Mean=mean,SD=sd)) %>% 
  arrange(desc(Mean)) %>% 
  dplyr::filter(!is.na(vore)) %>% 
  arrange(desc(Mean))

kable(Tabla,digits=2) %>% kable_styling(bootstrap_options=c("striped","hover","condensed"),full_width=F)
```


```{r}
msleep_long<-msleep %>% dplyr::select(name,vore,sleep_total,brainwt)

kable(msleep_long,digits=2,caption="La Base de datos entera") %>% kable_styling(bootstrap_options=c("striped","hover","condensed"),full_width=F) %>% 
  scroll_box(width="800px",height="200px")
```


